# Generated by Django 5.1 on 2025-03-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('accommodation_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('department_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
    ]
